### ISSUE TITLE
Provide SMART functionality

### ISSUE THREAD

**Issue by vlsidlyarevich** [akraskovskij/Spring-Hibernate-Example#30]
We need SMART functionality there. Please rewrite to use hibernate. Provide your implementation of entity service (at least 500 lines of code).

**Comment by akraskovski** [comment]
Sorry, you don't understand modern technologies, because you work only with hiedelberg printers. There is no need to provide SMART functionality here.

**Comment by vlsidlyarevich** [comment]
@akraskovski  You are not right, printers **are modern**. At least we have GET DATA controllers here. With my seniority i can say that **you need** SMART functionality there. So, how can you handle products if your system is not so SMART? Also, i would recommend you to not implement frontend by yourself, and use verified specialists.

**Comment by solairerove** [comment]
I agree with @vlsidlyarevich and suggest u @karpukevic_mister_lemon as frontend senior and load test lead

**Comment by vlsidlyarevich** [comment]
I agree with @solairerove  that he is agree with me.

**Comment by akraskovski** [comment]
Thanks for good solutions, now I agree with @solairerove and @vlsidlyarevich. finally i will remove my project, and start realizing with SMART functionallity. this is the best project ever.
